# Site settings
title: R Contour
email: homerhanumatATgmailDOTcom
description: > # this means to ignore newlines until "baseurl:"
  A blog devoted mostly to the the teaching of undergraduate-level statstics
  and data anlysis with R, along with occasional technical notes on R-related
  tools.
url: "https://homerhanumat.github.io" # the base hostname & protocol for your site
github_username:  homerhanumat
permalink: /:year/:month/:day/:title.html
author:  Homer White

baseurl: "/" # the sub-path of your site, e.g. /myProject/
                        # not standard for gh-pages, used for knitr
baseurlstrip:  "" # to generate standard links

# Disqus comments:
disqus:           true
shortname:        homerhanumatgithubio

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post

# Build settings

# rendering engine
markdown: kramdown

author:
  name:           'Homer White'
  url:            https://statistics.rainandrhino.org

github:
  repo:           https://github.com/homerhanumat/homerhanumat.github.io
